# Generated by Django 6.0 on 2026-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
