# Generated by Django 6.0.3 on 2026-08-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_transfer_company_subscription_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_url',
            field=models.URLField(blank=True, help_text='Link to Stripe-hosted invoice', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('manual', 'Manual')], default='stripe', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual price in GBP (optional override)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Annual')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID (price_xxx)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID (prod_xxx)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_period_days',
            field=models.IntegerField(default=7, help_text='Free trial days for new subscribers'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Annual')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='event_type',
            field=models.CharField(default='', help_text='e.g. invoice.paid, checkout.session.completed', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(help_text='Amount in smallest currency unit (pence for GBP)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='GBP', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, help_text='Price in GBP', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('GRACE', 'Grace Period'), ('PAST_DUE', 'Past Due'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended'), ('INCOMPLETE', 'Incomplete')], default='TRIAL', max_length=20),
        ),
    ]
