# Generated by Django 6.0 on 2026-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_address_company_city_company_is_ai_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='erp_password',
            field=models.CharField(blank=True, help_text='Temporary password for desktop ERP access', max_length=128, null=True),
        ),
    ]
