# Generated by Django 6.0 on 2026-04-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_erp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.CharField(default='UGX', help_text='Default display currency', max_length=10),
        ),
    ]
