# Generated by Django 6.0.3 on 2026-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
