# Generated by Django 6.0.3 on 2026-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
