# Generated by Django 6.0 on 2026-07-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_subscription_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='subscription_reminder_sent',
            new_name='expiry_email_sent',
        ),
        migrations.RemoveField(
            model_name='company',
            name='trial_reminder_sent',
        ),
    ]
