# Generated by Django 6.0 on 2026-07-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_rename_subscription_reminder_sent_company_expiry_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
