# Generated by Django 6.0.3 on 2026-08-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_reminder_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID (cus_xxx)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, help_text='Legacy Razorpay customer ID', max_length=100, null=True),
        ),
    ]
