# Generated by Django 6.0 on 2026-04-01 12:59

import django.db.models.deletion
import erp_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_erp_password'),
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default=erp_core.models.generate_account_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet')], default='cash', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='companies.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='erp_core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=erp_core.models.generate_customer_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('source', models.CharField(default='POS', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='erp_core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=erp_core.models.generate_product_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('min_stock', models.IntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_kit', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='erp_core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(default=erp_core.models.generate_sale_id, max_length=50, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('type', models.CharField(default='retail', max_length=50)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('items', models.JSONField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(max_length=50)),
                ('source', models.CharField(default='POS', max_length=50)),
                ('date', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_core.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='erp_core.store')),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.CharField(default=erp_core.models.generate_log_id, max_length=50, primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='erp_core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=erp_core.models.generate_trans_id, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_core.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='erp_core.store')),
            ],
        ),
    ]
