# Generated by Django 6.0 on 2026-04-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_erp_password'),
        ('erp_core', '0002_account_customer_product_sale_stocklog_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_categories', to='companies.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_categories', to='erp_core.store')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
