# Generated by Django 6.0 on 2026-04-04 12:47

import django.db.models.deletion
import erp_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_erp_password'),
        ('erp_core', '0004_alter_erpuser_first_name_alter_erpuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_serialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.CharField(default=erp_core.models.generate_tax_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.store')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tax_slab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_core.taxslab'),
        ),
    ]
