# Generated by Django 6.0 on 2026-04-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0005_product_discount_pct_product_is_serialized_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_pct',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
