# Generated by Django 6.0 on 2026-04-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0007_customfield_expensecategory_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='erp_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='erp_core.erpuser'),
        ),
    ]
