# Generated by Django 6.0 on 2026-04-06 19:07

import django.db.models.deletion
from django.db import migrations, models


def cleanup_invalid_categories(apps, schema_editor):
    Product = apps.get_model('erp_core', 'Product')
    Category = apps.get_model('erp_core', 'Category')
    # Get all category IDs that currently exist
    valid_category_ids = set(Category.objects.values_list('id', flat=True))
    # Reset any product category that references a non-existent ID
    # Note: in the migration history, 'category' is still a CharField here.
    for prod in Product.objects.all():
        if prod.category and prod.category not in valid_category_ids:
            print(f"[MIGRATION] Resetting invalid category '{prod.category}' for product {prod.id}")
            prod.category = None
            prod.save(update_fields=['category'])

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_erp_password'),
        ('erp_core', '0008_employee_erp_user_nullable'),
    ]

    operations = [
        migrations.AddField(model_name='account', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='attendance', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='candidate', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='category', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='cheque', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='commission', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='customer', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='customfield', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='delivery', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='deliveryzone', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='erpuser', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='erpuserpermission', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='expensecategory', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='giftcard', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='invoice', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='invoiceitem', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='itemkit', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='kititem', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='leave', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='loyaltypoint', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='paymentterm', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='payroll', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='performancereview', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='product', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='productcustomvalue', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='purchase', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='purchaseorder', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='quotation', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='receiving', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='receivingitem', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='sale', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='salepayment', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='setting', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='shift', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='stocklog', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='stocktransfer', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='store', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='supplier', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='suppliercustomfield', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='suppliercustomfieldvalue', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='supplierdocument', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='suppliertransaction', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='taxslab', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='transaction', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='userstore', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='workorder', name='deleted_at', field=models.DateTimeField(blank=True, null=True)),
        
        # ── DATA CLEANUP BEFORE FOREIGN KEY CONSTRAINT ──────────────────────
        migrations.RunPython(cleanup_invalid_categories, reverse_code=migrations.RunPython.noop),
        
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='erp_core.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'store'], name='erp_core_ca_company_b56270_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'store'], name='erp_core_pr_company_21477f_idx'),
        ),
    ]
