# Generated by Django 6.0 on 2026-04-07 09:46

import django.db.models.deletion
import erp_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_erp_password'),
        ('erp_core', '0009_account_deleted_at_attendance_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='itemkit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments_core', to='companies.company'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments_core', to='erp_core.store'),
        ),
        migrations.AddField(
            model_name='shift',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_core.store'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_core.store'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_core.store'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_core.store'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_core.store'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='receivingitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='receivingitem',
            name='id',
            field=models.CharField(default=erp_core.models.generate_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receivingitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_core.store'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'store'], name='erp_core_ac_company_d83451_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['company', 'store'], name='erp_core_ca_company_f49c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['company', 'store'], name='erp_core_ch_company_638193_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'store'], name='erp_core_cu_company_c3565e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['company', 'store'], name='erp_core_de_company_e7a010_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['company', 'store'], name='erp_core_de_company_25a137_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['company', 'store'], name='erp_core_gi_company_093ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='itemkit',
            index=models.Index(fields=['company', 'store'], name='erp_core_it_company_9edae4_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['company', 'store'], name='erp_core_pe_company_7d6b64_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'store'], name='erp_core_sa_company_c19980_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['company', 'store'], name='erp_core_sa_company_a0d9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['company', 'store'], name='erp_core_sh_company_6bf9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['company', 'store'], name='erp_core_st_company_0f4303_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliertransaction',
            index=models.Index(fields=['company', 'store'], name='erp_core_su_company_faacea_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'store'], name='erp_core_tr_company_1384e9_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['company', 'store'], name='erp_core_wo_company_ee8ec6_idx'),
        ),
    ]
