# Generated by Django 6.0 on 2026-04-07 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_erp_password'),
        ('erp_core', '0010_candidate_company_delivery_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='erp_core.store'),
        ),
        migrations.AlterField(
            model_name='receivingitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_items', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='receivingitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_items', to='erp_core.store'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_transactions', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_transactions', to='erp_core.store'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'store'], name='erp_core_in_company_c88fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'store'], name='erp_core_pu_company_cd363c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'store'], name='erp_core_pu_company_c2698a_idx'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['company', 'store'], name='erp_core_re_company_943766_idx'),
        ),
        migrations.AddIndex(
            model_name='receivingitem',
            index=models.Index(fields=['company', 'store'], name='erp_core_re_company_f172d9_idx'),
        ),
    ]
