# Generated by Django 6.0 on 2026-04-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_erp_password'),
        ('erp_core', '0011_alter_invoice_company_alter_invoice_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='companies.company'),
        ),
        migrations.AddField(
            model_name='commission',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='erp_core.store'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='companies.company'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='erp_core.store'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='companies.company'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='erp_core.store'),
        ),
        migrations.AddField(
            model_name='kititem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='companies.company'),
        ),
        migrations.AddField(
            model_name='kititem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='erp_core.store'),
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to='companies.company'),
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to='erp_core.store'),
        ),
        migrations.AddField(
            model_name='productcustomvalue',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_custom_values', to='companies.company'),
        ),
        migrations.AddField(
            model_name='productcustomvalue',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_custom_values', to='erp_core.store'),
        ),
        migrations.AddField(
            model_name='suppliercustomfield',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_custom_fields', to='companies.company'),
        ),
        migrations.AddField(
            model_name='suppliercustomfieldvalue',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_custom_values', to='companies.company'),
        ),
        migrations.AddField(
            model_name='suppliercustomfieldvalue',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_custom_values', to='erp_core.store'),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_documents', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['company', 'store'], name='erp_core_co_company_380aba_idx'),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['company', 'store'], name='erp_core_cu_company_192609_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['company', 'store'], name='erp_core_ex_company_4cfe9c_idx'),
        ),
        migrations.AddIndex(
            model_name='kititem',
            index=models.Index(fields=['company', 'store'], name='erp_core_ki_company_908c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypoint',
            index=models.Index(fields=['company', 'store'], name='erp_core_lo_company_0048ee_idx'),
        ),
        migrations.AddIndex(
            model_name='productcustomvalue',
            index=models.Index(fields=['company', 'store'], name='erp_core_pr_company_7b92e6_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercustomfield',
            index=models.Index(fields=['company', 'store'], name='erp_core_su_company_4438cb_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercustomfieldvalue',
            index=models.Index(fields=['company', 'store'], name='erp_core_su_company_9e33e9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdocument',
            index=models.Index(fields=['company', 'store'], name='erp_core_su_company_8f6018_idx'),
        ),
    ]
