# Generated by Django 6.0 on 2026-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0012_commission_company_commission_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
