# Generated by Django 6.0 on 2026-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0013_employee_email_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('bank', 'Bank'), ('savings', 'Savings'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
    ]
