# Generated by Django 6.0 on 2026-04-10 14:34

import django.db.models.deletion
import erp_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_base_currency'),
        ('erp_core', '0014_alter_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=erp_core.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_rates', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'currency_code'], name='erp_core_cu_company_4720cc_idx')],
                'unique_together': {('company', 'currency_code')},
            },
        ),
    ]
