# Generated by Django 6.0 on 2026-04-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_base_currency'),
        ('erp_core', '0015_currencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiving',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='receiving',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='erp_core.store'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='receiving_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.UniqueConstraint(fields=('company', 'bank_name', 'cheque_number'), name='unique_cheque_per_company'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='unique_company_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='unique_company_purchase_invoice'),
        ),
        migrations.AddConstraint(
            model_name='receiving',
            constraint=models.UniqueConstraint(fields=('company', 'receiving_number'), name='unique_company_receiving_number'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='unique_company_sale_invoice'),
        ),
    ]
