# Generated by Django 6.0 on 2026-04-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_base_currency'),
        ('erp_core', '0016_invoice_original_amount_invoice_original_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='erp_core.store'),
        ),
    ]
