# Generated by Django 6.0 on 2026-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_base_currency'),
        ('erp_core', '0017_alter_cheque_company_alter_cheque_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'store'], name='erp_core_qu_company_fcfa72_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'quotation_number'), name='unique_company_quotation_number'),
        ),
    ]
