# Generated by Django 6.0 on 2026-04-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0018_quotation_original_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount the customer owes. Positive = Dues, Negative = Advance/Credit.', max_digits=15, verbose_name='Dues (Debit Balance)'),
        ),
    ]
