# Generated by Django 6.0 on 2026-04-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_base_currency'),
        ('erp_core', '0019_alter_customer_credit_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='erpuser',
            unique_together={('company', 'email'), ('company', 'username')},
        ),
    ]
