# Generated by Django 6.0 on 2026-04-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_base_currency'),
        ('erp_core', '0020_alter_erpuser_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('company', 'name')},
        ),
    ]
