# Generated by Django 6.0.3 on 2026-06-10 05:56

import django.db.models.deletion
import erp_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_base_currency'),
        ('erp_core', '0021_alter_store_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCustomValue',
            fields=[
                ('sync_status', models.IntegerField(default=0)),
                ('id', models.CharField(default=erp_core.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='customfield',
            name='erp_core_cu_company_192609_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcustomvalue',
            name='erp_core_pr_company_7b92e6_idx',
        ),
        migrations.AlterField(
            model_name='customfield',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productcustomvalue',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('company', 'label', 'target_type')},
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['company', 'store', 'target_type'], name='erp_core_cu_company_b91935_idx'),
        ),
        migrations.AddIndex(
            model_name='productcustomvalue',
            index=models.Index(fields=['company', 'store', 'product'], name='erp_core_pr_company_1bebce_idx'),
        ),
        migrations.AddField(
            model_name='salecustomvalue',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_custom_values', to='companies.company'),
        ),
        migrations.AddField(
            model_name='salecustomvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.customfield'),
        ),
        migrations.AddField(
            model_name='salecustomvalue',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.sale'),
        ),
        migrations.AddField(
            model_name='salecustomvalue',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_custom_values', to='erp_core.store'),
        ),
        migrations.AddIndex(
            model_name='salecustomvalue',
            index=models.Index(fields=['company', 'store', 'sale'], name='erp_core_sa_company_514b0a_idx'),
        ),
    ]
