# Generated by Django 6.0 on 2026-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_base_currency'),
        ('erp_core', '0022_salecustomvalue_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxslab',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='taxslab',
            index=models.Index(fields=['company', 'store'], name='erp_core_ta_company_f9948e_idx'),
        ),
    ]
