# Generated by Django 6.0 on 2026-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0023_alter_taxslab_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='card_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=100),
        ),
    ]
