# Generated by Django 6.0 on 2026-07-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0024_alter_giftcard_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_core.expensecategory'),
        ),
    ]
