# Generated by Django 6.0 on 2026-07-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0025_transaction_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='previous_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
